<div>
    <form class="admin__scope-old" action="<?= $block->escapeUrl($block->getFormAction()) ?>"
          id="edit_form" method="post" enctype="multipart/form-data">
        <input name="form_key" type="hidden" value="<?= $block->escapeHtml($block->getFormKey()) ?>"/>
        <fieldset class="admin__fieldset">
            <?= $block->getBlockHtml('formkey') ?>
            <?= $block->getChildHtml('form_fields') ?>
        </fieldset>
        <div class="admin__actions-toolbar">
            <div class="admin__form-left">
                <button class="action-default scalable" type="submit">
                    <span><?= $block->escapeHtml(__('Save')) ?></span>
                </button>
            </div>
            <div class="admin__form-right">
                <a class="action-secondary" href="<?= $block->escapeUrl($block->getBackUrl()) ?>">
                    <span><?= $block->escapeHtml(__('Back')) ?></span>
                </a>
            </div>
        </div>
    </form>
</div>
