<div>
    <form id="edit_form" method="post" action="<?= $block->getSaveUrl() ?>" enctype="multipart/form-data">
        <input name="form_key" type="hidden" value="<?= $block->getFormKey() ?>" />

        <fieldset class="admin__fieldset">
            <legend class="admin__legend"><?= __('Shop Information') ?></legend>
            <div class="admin__field">
                <label for="shop_name" class="admin__field-label"><?= __('Shop Name') ?></label>
                <div class="admin__field-control">
                    <input id="shop_name" name="shop[name]" type="text" class="input-text" />
                </div>
            </div>

            <div class="admin__field">
                <label for="shop_identifier" class="admin__field-label"><?= __('Identifier') ?></label>
                <div class="admin__field-control">
                    <input id="shop_identifier" name="shop[identifier]" type="text" class="input-text" />
                </div>
            </div>

            <div class="admin__field">
                <label for="shop_country" class="admin__field-label"><?= __('Country') ?></label>
                <div class="admin__field-control">
                    <select id="shop_country" name="shop[country]" class="select">
                        <?php foreach ($block->getCountries() as $country): ?>
                            <option value="<?= $country['value'] ?>"><?= $country['label'] ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>

            <div class="admin__field">
                <label for="shop_image" class="admin__field-label"><?= __('Image') ?></label>
                <div class="admin__field-control">
                    <input id="shop_image" name="shop[image]" type="file" class="input-file" />
                </div>
            </div>

            <div class="admin__field">
                <label for="shop_longitude" class="admin__field-label"><?= __('Longitude') ?></label>
                <div class="admin__field-control">
                    <input id="shop_longitude" name="shop[longitude]" type="text" class="input-text" />
                </div>
            </div>

            <div class="admin__field">
                <label for="shop_latitude" class="admin__field-label"><?= __('Latitude') ?></label>
                <div class="admin__field-control">
                    <input id="shop_latitude" name="shop[latitude]" type="text" class="input-text" />
                </div>
            </div>
        </fieldset>

        <div class="admin__actions">
            <button type="submit" class="action-primary">
                <span><?= __('Save Shop') ?></span>
            </button>
        </div>
    </form>
</div>
