<div>
    <h1><?= $block->escapeHtml(__('Shopfinder - Manage Shops')) ?></h1>
    <table class="data-grid">
        <thead>
        <tr>
            <th><?= __('ID') ?></th>
            <th><?= __('Image') ?></th>
            <th><?= __('Shop Name') ?></th>
            <th><?= __('Identifier') ?></th>
            <th><?= __('Country') ?></th>
            <th><?= __('Created') ?></th>
            <th><?= __('Modified') ?></th>
            <th><?= __('Action') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($block->getShops() as $shop): ?>
            <tr>
                <td><?= $block->escapeHtml($shop->getId()) ?></td>
                <td><?= $block->escapeHtml($shop->getImage()) ?></td>
                <td><?= $block->escapeHtml($shop->getName()) ?></td>
                <td><?= $block->escapeHtml($shop->getIdentifier()) ?></td>
                <td><?= $block->escapeHtml($shop->getCountry()) ?></td>
                <td><?= $block->escapeHtml($shop->getCreatedAt()) ?></td>
                <td><?= $block->escapeHtml($shop->getUpdatedAt()) ?></td>
                <td>
                    <a href="<?= $block->getUrl('shopfinder/shop/edit', ['id' => $shop->getId()]) ?>">
                        <?= __('Edit') ?>
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
